require_relative 'toycol/generator'

namespace :toycol do
  desc 'create template for new protocol'
  task :new_protocol, %i[name] do |_task, args|
    puts "Generating new protocol and app..."

    Toycol::Generator.execute!(:protocol, name: args.name, dir: __dir__)
    Toycol::Generator.execute!(:app, name: args.name, dir: __dir__)

    puts "Successed to generate:"

    puts Dir.glob("./protocols/*.rb")
    puts Dir.glob("./config_#{args.name.to_s}.ru")
  end
end
