#use "q08_05.ml" ;;

let global_between_list = [
  {start_with="代々木上原"; end_with="代々木公園"; via="千代田線"; distance=1.0; min=2};
  {start_with="代々木公園"; end_with="明治神宮前"; via="千代田線"; distance=1.2; min=2};
  {start_with="明治神宮前"; end_with="表参道"; via="千代田線"; distance=0.9; min=2};
  {start_with="表参道"; end_with="乃木坂"; via="千代田線"; distance=1.4; min=3};
  {start_with="乃木坂"; end_with="赤坂"; via="千代田線"; distance=1.1; min=2};
  {start_with="赤坂"; end_with="国会議事堂前"; via="千代田線"; distance=0.8; min=1};
  {start_with="国会議事堂前"; end_with="霞ヶ関"; via="千代田線"; distance=0.7; min=1};
  {start_with="霞ヶ関"; end_with="日比谷"; via="千代田線"; distance=1.2; min=2};
  {start_with="日比谷"; end_with="二重橋前"; via="千代田線"; distance=0.7; min=1};
  {start_with="二重橋前"; end_with="大手町"; via="千代田線"; distance=0.7; min=1};
  {start_with="大手町"; end_with="新御茶ノ水"; via="千代田線"; distance=1.3; min=2};
  {start_with="新御茶ノ水"; end_with="湯島"; via="千代田線"; distance=1.2; min=2};
  {start_with="湯島"; end_with="根津"; via="千代田線"; distance=1.2; min=2};
  {start_with="根津"; end_with="千駄木"; via="千代田線"; distance=1.0; min=2};
  {start_with="千駄木"; end_with="西日暮里"; via="千代田線"; distance=0.9; min=1};
  {start_with="西日暮里"; end_with="町屋"; via="千代田線"; distance=1.7; min=2};
  {start_with="町屋"; end_with="北千住"; via="千代田線"; distance=2.6; min=3};
  {start_with="北千住"; end_with="綾瀬"; via="千代田線"; distance=2.5; min=3};
  {start_with="綾瀬"; end_with="北綾瀬"; via="千代田線"; distance=2.1; min=4};
  {start_with="浅草"; end_with="田原町"; via="銀座線"; distance=0.8; min=2};
  {start_with="田原町"; end_with="稲荷町"; via="銀座線"; distance=0.7; min=1};
  {start_with="稲荷町"; end_with="上野"; via="銀座線"; distance=0.7; min=2};
  {start_with="上野"; end_with="上野広小路"; via="銀座線"; distance=0.5; min=2};
  {start_with="上野広小路"; end_with="末広町"; via="銀座線"; distance=0.6; min=1};
  {start_with="末広町"; end_with="神田"; via="銀座線"; distance=1.1; min=2};
  {start_with="神田"; end_with="三越前"; via="銀座線"; distance=0.7; min=1};
  {start_with="三越前"; end_with="日本橋"; via="銀座線"; distance=0.6; min=2};
  {start_with="日本橋"; end_with="京橋"; via="銀座線"; distance=0.7; min=2};
  {start_with="京橋"; end_with="銀座"; via="銀座線"; distance=0.7; min=1};
  {start_with="銀座"; end_with="新橋"; via="銀座線"; distance=0.9; min=2};
  {start_with="新橋"; end_with="虎ノ門"; via="銀座線"; distance=0.8; min=2};
  {start_with="虎ノ門"; end_with="溜池山王"; via="銀座線"; distance=0.6; min=2};
  {start_with="溜池山王"; end_with="赤坂見附"; via="銀座線"; distance=0.9; min=2};
  {start_with="赤坂見附"; end_with="青山一丁目"; via="銀座線"; distance=1.3; min=2};
  {start_with="青山一丁目"; end_with="外苑前"; via="銀座線"; distance=0.7; min=2};
  {start_with="外苑前"; end_with="表参道"; via="銀座線"; distance=0.7; min=1};
  {start_with="表参道"; end_with="渋谷"; via="銀座線"; distance=1.3; min=1};
  {start_with="渋谷"; end_with="表参道"; via="半蔵門線"; distance=1.3; min=2};
  {start_with="表参道"; end_with="青山一丁目"; via="半蔵門線"; distance=1.4; min=2};
  {start_with="青山一丁目"; end_with="永田町"; via="半蔵門線"; distance=1.3; min=2};
  {start_with="永田町"; end_with="半蔵門"; via="半蔵門線"; distance=1.0; min=2};
  {start_with="半蔵門"; end_with="九段下"; via="半蔵門線"; distance=1.6; min=2};
  {start_with="九段下"; end_with="神保町"; via="半蔵門線"; distance=0.4; min=1};
  {start_with="神保町"; end_with="大手町"; via="半蔵門線"; distance=1.7; min=3};
  {start_with="大手町"; end_with="三越前"; via="半蔵門線"; distance=0.7; min=1};
  {start_with="三越前"; end_with="水天宮前"; via="半蔵門線"; distance=1.3; min=2};
  {start_with="水天宮前"; end_with="清澄白河"; via="半蔵門線"; distance=1.7; min=3};
  {start_with="清澄白河"; end_with="住吉"; via="半蔵門線"; distance=1.9; min=3};
  {start_with="住吉"; end_with="錦糸町"; via="半蔵門線"; distance=1.; min=2};
  {start_with="錦糸町"; end_with="押上"; via="半蔵門線"; distance=1.4; min=2};
  {start_with="中目黒"; end_with="恵比寿"; via="日比谷線"; distance=1.; min=2};
  {start_with="恵比寿"; end_with="広尾"; via="日比谷線"; distance=1.5; min=3};
  {start_with="広尾"; end_with="六本木"; via="日比谷線"; distance=1.7; min=3};
  {start_with="六本木"; end_with="神谷町"; via="日比谷線"; distance=1.5; min=3};
  {start_with="神谷町"; end_with="霞ヶ関"; via="日比谷線"; distance=1.3; min=2};
  {start_with="霞ヶ関"; end_with="日比谷"; via="日比谷線"; distance=1.2; min=2};
  {start_with="日比谷"; end_with="銀座"; via="日比谷線"; distance=0.4; min=1};
  {start_with="銀座"; end_with="東銀座"; via="日比谷線"; distance=0.4; min=1};
  {start_with="東銀座"; end_with="築地"; via="日比谷線"; distance=0.6; min=2};
  {start_with="築地"; end_with="八丁堀"; via="日比谷線"; distance=1.; min=2};
  {start_with="八丁堀"; end_with="茅場町"; via="日比谷線"; distance=0.5; min=1};
  {start_with="茅場町"; end_with="人形町"; via="日比谷線"; distance=0.9; min=2};
  {start_with="人形町"; end_with="小伝馬町"; via="日比谷線"; distance=0.6; min=1};
  {start_with="小伝馬町"; end_with="秋葉原"; via="日比谷線"; distance=0.9; min=2};
  {start_with="秋葉原"; end_with="仲御徒町"; via="日比谷線"; distance=1.; min=1};
  {start_with="仲御徒町"; end_with="上野"; via="日比谷線"; distance=0.5; min=1};
  {start_with="上野"; end_with="入谷"; via="日比谷線"; distance=1.2; min=2};
  {start_with="入谷"; end_with="三ノ輪"; via="日比谷線"; distance=1.2; min=2};
  {start_with="三ノ輪"; end_with="南千住"; via="日比谷線"; distance=0.8; min=2};
  {start_with="南千住"; end_with="北千住"; via="日比谷線"; distance=1.8; min=3};
  {start_with="池袋"; end_with="新大塚"; via="丸ノ内線"; distance=1.8; min=3};
  {start_with="新大塚"; end_with="茗荷谷"; via="丸ノ内線"; distance=1.2; min=2};
  {start_with="茗荷谷"; end_with="後楽園"; via="丸ノ内線"; distance=1.8; min=2};
  {start_with="後楽園"; end_with="本郷三丁目"; via="丸ノ内線"; distance=0.8; min=1};
  {start_with="本郷三丁目"; end_with="御茶ノ水"; via="丸ノ内線"; distance=0.8; min=1};
  {start_with="御茶ノ水"; end_with="淡路町"; via="丸ノ内線"; distance=0.8; min=1};
  {start_with="淡路町"; end_with="大手町"; via="丸ノ内線"; distance=0.9; min=2};
  {start_with="大手町"; end_with="東京"; via="丸ノ内線"; distance=0.6; min=1};
  {start_with="東京"; end_with="銀座"; via="丸ノ内線"; distance=1.1; min=2};
  {start_with="銀座"; end_with="霞ヶ関"; via="丸ノ内線"; distance=1.0; min=2};
  {start_with="霞ヶ関"; end_with="国会議事堂前"; via="丸ノ内線"; distance=0.7; min=1};
  {start_with="国会議事堂前"; end_with="赤坂見附"; via="丸ノ内線"; distance=0.9; min=2};
  {start_with="赤坂見附"; end_with="四ツ谷"; via="丸ノ内線"; distance=1.3; min=2};
  {start_with="四ツ谷"; end_with="四谷三丁目"; via="丸ノ内線"; distance=1.0; min=2};
  {start_with="四谷三丁目"; end_with="新宿御苑前"; via="丸ノ内線"; distance=0.9; min=1};
  {start_with="新宿御苑前"; end_with="新宿三丁目"; via="丸ノ内線"; distance=0.7; min=1};
  {start_with="新宿三丁目"; end_with="新宿"; via="丸ノ内線"; distance=0.3; min=1};
  {start_with="新宿"; end_with="西新宿"; via="丸ノ内線"; distance=0.8; min=1};
  {start_with="西新宿"; end_with="中野坂上"; via="丸ノ内線"; distance=1.1; min=2};
  {start_with="中野坂上"; end_with="新中野"; via="丸ノ内線"; distance=1.1; min=2};
  {start_with="新中野"; end_with="東高円寺"; via="丸ノ内線"; distance=1.0; min=1};
  {start_with="東高円寺"; end_with="新高円寺"; via="丸ノ内線"; distance=0.9; min=1};
  {start_with="新高円寺"; end_with="南阿佐ヶ谷"; via="丸ノ内線"; distance=1.2; min=2};
  {start_with="南阿佐ヶ谷"; end_with="荻窪"; via="丸ノ内線"; distance=1.5; min=2};
  {start_with="中野坂上"; end_with="中野新橋"; via="丸ノ内線"; distance=1.3; min=2};
  {start_with="中野新橋"; end_with="中野富士見町"; via="丸ノ内線"; distance=0.6; min=1};
  {start_with="中野富士見町"; end_with="方南町"; via="丸ノ内線"; distance=1.3; min=2};
  {start_with="市ヶ谷"; end_with="四ツ谷"; via="南北線"; distance=1.0; min=2};
  {start_with="四ツ谷"; end_with="永田町"; via="南北線"; distance=1.3; min=3};
  {start_with="永田町"; end_with="溜池山王"; via="南北線"; distance=0.9; min=1};
  {start_with="溜池山王"; end_with="六本木一丁目"; via="南北線"; distance=0.9; min=2};
  {start_with="六本木一丁目"; end_with="麻布十番"; via="南北線"; distance=1.2; min=2};
  {start_with="麻布十番"; end_with="白金高輪"; via="南北線"; distance=1.3; min=2};
  {start_with="白金高輪"; end_with="白金台"; via="南北線"; distance=1.0; min=2};
  {start_with="白金台"; end_with="目黒"; via="南北線"; distance=1.3; min=2};
  {start_with="市ヶ谷"; end_with="飯田橋"; via="南北線"; distance=1.1 ; min=2};
  {start_with="飯田橋"; end_with="後楽園"; via="南北線"; distance=1.4 ; min=2};
  {start_with="後楽園"; end_with="東大前"; via="南北線"; distance=1.3 ; min=3};
  {start_with="東大前"; end_with="本駒込"; via="南北線"; distance=0.9 ; min=2};
  {start_with="本駒込"; end_with="駒込"; via="南北線"; distance=1.4; min=2};
  {start_with="駒込"; end_with="西ヶ原"; via="南北線"; distance=1.4; min=2};
  {start_with="西ヶ原"; end_with="王子"; via="南北線"; distance=1.0; min=2};
  {start_with="王子"; end_with="王子神谷"; via="南北線"; distance=1.2; min=2};
  {start_with="王子神谷"; end_with="志茂"; via="南北線"; distance=1.6; min=3};
  {start_with="志茂"; end_with="赤羽岩淵"; via="南北線"; distance=1.1; min=2};
  {start_with="西船橋" ; end_with="原木中山"; via="東西線"; distance=1.9; min=3};
  {start_with="原木中山"; end_with="妙典"; via="東西線"; distance=2.1 ; min=2};
  {start_with="妙典"; end_with="行徳"; via="東西線"; distance=1.3 ; min=2};
  {start_with="行徳"; end_with="南行徳"; via="東西線"; distance=1.5 ; min=2};
  {start_with="南行徳"; end_with="浦安" ; via="東西線"; distance=1.2 ; min=2};
  {start_with="浦安" ; end_with="葛西"; via="東西線"; distance=1.9 ; min=2};
  {start_with="葛西"; end_with="西葛西"; via="東西線"; distance=1.2 ; min=2};
  {start_with="西葛西"; end_with="南砂町"; via="東西線"; distance=2.7 ; min=2};
  {start_with="南砂町"; end_with="東陽町"; via="東西線"; distance=1.2 ; min=2};
  {start_with="東陽町"; end_with="木場" ; via="東西線"; distance=0.9 ; min=1};
  {start_with="木場"; end_with="門前仲町"; via="東西線"; distance=1.1 ; min=1};
  {start_with="門前仲町"; end_with="茅場町"; via="東西線"; distance=1.8 ; min=2};
  {start_with="茅場町"; end_with="日本橋"; via="東西線"; distance=0.5 ; min=1};
  {start_with="日本橋"; end_with="大手町"; via="東西線"; distance=0.8 ; min=1};
  {start_with="大手町"; end_with="竹橋"; via="東西線"; distance=1.0; min=2};
  {start_with="竹橋"; end_with="九段下"; via="東西線"; distance=1.0; min=1};
  {start_with="九段下"; end_with="飯田橋"; via="東西線"; distance=0.7; min=1};
  {start_with="飯田橋"; end_with="神楽坂"; via="東西線"; distance=1.2; min=2};
  {start_with="神楽坂"; end_with="早稲田"; via="東西線"; distance=1.2; min=2};
  {start_with="早稲田"; end_with="高田馬場"; via="東西線"; distance=1.7; min=3};
  {start_with="高田馬場"; end_with="落合"; via="東西線"; distance=1.9; min=3};
  {start_with="落合"; end_with="中野"; via="東西線"; distance=2.0; min=3};
  {start_with="新木場"; end_with="辰巳"; via="有楽町線"; distance=1.5; min=2};
  {start_with="辰巳"; end_with="豊洲"; via="有楽町線"; distance=1.7; min=2};
  {start_with="豊洲"; end_with="月島"; via="有楽町線"; distance=1.4; min=2};
  {start_with="月島"; end_with="新富町"; via="有楽町線"; distance=1.3; min=2};
  {start_with="新富町"; end_with="銀座一丁目"; via="有楽町線"; distance=0.7; min=1};
  {start_with="銀座一丁目"; end_with="有楽町"; via="有楽町線"; distance=0.5; min=1};
  {start_with="有楽町"; end_with="桜田門"; via="有楽町線"; distance=1.0; min=1};
  {start_with="桜田門"; end_with="永田町"; via="有楽町線"; distance=0.9; min=2};
  {start_with="永田町"; end_with="麹町"; via="有楽町線"; distance=0.9; min=1};
  {start_with="麹町"; end_with="市ヶ谷"; via="有楽町線"; distance=0.9; min=1};
  {start_with="市ヶ谷"; end_with="飯田橋"; via="有楽町線"; distance=1.1; min=2};
  {start_with="飯田橋"; end_with="江戸川橋"; via="有楽町線"; distance=1.6; min=3};
  {start_with="江戸川橋"; end_with="護国寺"; via="有楽町線"; distance=1.3; min=2};
  {start_with="護国寺"; end_with="東池袋"; via="有楽町線"; distance=1.1; min=2};
  {start_with="東池袋"; end_with="池袋"; via="有楽町線"; distance=2.0; min=2};
  {start_with="池袋"; end_with="要町"; via="有楽町線"; distance=1.2; min=2};
  {start_with="要町"; end_with="千川"; via="有楽町線"; distance=1.0; min=1};
  {start_with="千川"; end_with="小竹向原"; via="有楽町線"; distance=1.0; min=2};
  {start_with="小竹向原"; end_with="氷川台"; via="有楽町線"; distance=1.5; min=2};
  {start_with="氷川台"; end_with="平和台"; via="有楽町線"; distance=1.4; min=2};
  {start_with="平和台"; end_with="営団赤塚"; via="有楽町線"; distance=1.8; min=2};
  {start_with="営団赤塚"; end_with="営団成増"; via="有楽町線"; distance=1.5; min=2};
  {start_with="営団成増"; end_with="和光市"; via="有楽町線"; distance=2.1; min=3};
]
