require "httparty"

GEM_PATH = ENV["RBENV_ROOT"] + "/versions/" + ENV["RBENV_VERSION"] + "/lib/ruby/gems/"

TracePoint.trace(:call) do |tp|
  if tp.path.include? "httparty"
    p [tp.self.class, tp.defined_class, tp.method_id, "#{tp.path.gsub(GEM_PATH, "")}:#{tp.lineno}"]
  end
end

HTTParty.get("https://example.com/")

__END__
[Module, #<Class:HTTParty>, :get, "3.4.0/gems/httparty-0.22.0/lib/httparty.rb:643"]
[Class, HTTParty::ClassMethods, :get, "3.4.0/gems/httparty-0.22.0/lib/httparty.rb:520"]
[Class, HTTParty::ClassMethods, :perform_request, "3.4.0/gems/httparty-0.22.0/lib/httparty.rb:610"]
[Class, HTTParty::ClassMethods, :build_request, "3.4.0/gems/httparty-0.22.0/lib/httparty.rb:589"]
[Module, #<Class:HTTParty::ModuleInheritableAttributes>, :hash_deep_dup, "3.4.0/gems/httparty-0.22.0/lib/httparty/module_inheritable_attributes.rb:10"]
[Class, HTTParty::ClassMethods, :headers, "3.4.0/gems/httparty-0.22.0/lib/httparty.rb:231"]
[HTTParty::HeadersProcessor, HTTParty::HeadersProcessor, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/headers_processor.rb:7"]
[HTTParty::HeadersProcessor, HTTParty::HeadersProcessor, :call, "3.4.0/gems/httparty-0.22.0/lib/httparty/headers_processor.rb:12"]
[Class, HTTParty::ClassMethods, :process_cookies, "3.4.0/gems/httparty-0.22.0/lib/httparty.rb:614"]
[HTTParty::Request, HTTParty::Request, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:61"]
[HTTParty::Request, HTTParty::Request, :path=, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:79"]
[HTTParty::Request, HTTParty::Request, :set_basic_auth_from_uri, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:413"]
[HTTParty::Request, HTTParty::Request, :perform, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:150"]
[HTTParty::Request, HTTParty::Request, :validate, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:399"]
[HTTParty::Request, HTTParty::Request, :post?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:409"]
[HTTParty::Request, HTTParty::Request, :setup_raw_request, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:224"]
[HTTParty::Request, HTTParty::Request, :uri, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:100"]
[HTTParty::Request, HTTParty::Request, :query_string, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:277"]
[HTTParty::Request, HTTParty::Request, :request_uri, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:92"]
[HTTParty::Request, HTTParty::Request, :decompress_content?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:261"]
[HTTParty::Request, HTTParty::Request, :digest_auth?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:257"]
[HTTParty::Request, HTTParty::Request, :http, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:196"]
[HTTParty::Request, HTTParty::Request, :connection_adapter, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:146"]
[HTTParty::Request, HTTParty::Request, :uri, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:100"]
[HTTParty::Request, HTTParty::Request, :query_string, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:277"]
[Class, #<Class:HTTParty::ConnectionAdapter>, :call, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:79"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:91"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :connection, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:99"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :clean_host, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:173"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :strip_ipv6_brackets, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:177"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :ssl_implied?, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:181"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :attach_ssl_certificates, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:189"]
[Class, #<Class:HTTParty::ConnectionAdapter>, :default_cert_store, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:83"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :add_timeout?, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:165"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :add_timeout?, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:165"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :add_timeout?, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:165"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :add_timeout?, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:165"]
[HTTParty::ConnectionAdapter, HTTParty::ConnectionAdapter, :add_max_retries?, "3.4.0/gems/httparty-0.22.0/lib/httparty/connection_adapter.rb:169"]
[HTTParty::Request, HTTParty::Request, :response_redirects?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:359"]
[HTTParty::Request, HTTParty::Request, :handle_unauthorized, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:176"]
[HTTParty::Request, HTTParty::Request, :digest_auth?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:257"]
[HTTParty::Request, HTTParty::Request, :handle_response, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:296"]
[HTTParty::Request, HTTParty::Request, :response_redirects?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:359"]
[HTTParty::Request, HTTParty::Request, :decompress, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:421"]
[HTTParty::Decompressor, HTTParty::Decompressor, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/decompressor.rb:34"]
[HTTParty::Decompressor, HTTParty::Decompressor, :decompress, "3.4.0/gems/httparty-0.22.0/lib/httparty/decompressor.rb:42"]
[HTTParty::Request, HTTParty::Request, :encode_text, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:425"]
[HTTParty::Request, HTTParty::Request, :assume_utf16_is_big_endian, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:292"]
[HTTParty::TextEncoder, HTTParty::TextEncoder, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/text_encoder.rb:7"]
[HTTParty::TextEncoder, HTTParty::TextEncoder, :call, "3.4.0/gems/httparty-0.22.0/lib/httparty/text_encoder.rb:13"]
[HTTParty::TextEncoder, HTTParty::TextEncoder, :can_encode?, "3.4.0/gems/httparty-0.22.0/lib/httparty/text_encoder.rb:23"]
[HTTParty::TextEncoder, HTTParty::TextEncoder, :charset, "3.4.0/gems/httparty-0.22.0/lib/httparty/text_encoder.rb:60"]
[HTTParty::Request, HTTParty::Request, :decompress_content?, "3.4.0/gems/httparty-0.22.0/lib/httparty/request.rb:261"]
[HTTParty::Response, HTTParty::Response, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/response.rb:17"]
[HTTParty::Response::Headers, HTTParty::Response::Headers, :initialize, "3.4.0/gems/httparty-0.22.0/lib/httparty/response/headers.rb:10"]
[HTTParty::Response, HTTParty::Response, :throw_exception, "3.4.0/gems/httparty-0.22.0/lib/httparty/response.rb:135"]
