hfcal.o: p366_hfcal.c
	gcc -I/includes -c p366_hfcal.c -o hfcal.o
main.o: p366_main.c
	gcc -I/includes -c p366_main.c -o main.o
libhfcal.a: hfcal.o
	ar -rcs /includes/libs/libhfcal.a hfcal.o
main: libhfcal.a main.o
	gcc main.o -L/includes/libs -lhfcal -o main
